### ISSUE TITLE
Charging pins

### ISSUE THREAD

**Issue by shmick** [Thijsiez/braunit-charger#1]
Would you happen to know what pins on the Braunit battery are used for charging with 8.4v?

**Comment by Thijsiez** [comment]
Hej Steve,

Actually, I do! For this project I fully reverse-engineered the electronics in the battery packs and a charger (contained in an IKEA Bluetooth speaker), I just haven't documented that anywhere. This project fell by the wayside and I started doing other stuff.

Anyway, if you look at the micro USB port, with the 4-pin blade connector facing up, the left pin (closest to the USB connector) will be your pack positive, directly connected to the cell positive.
The right pin (farthest away from the USB connector) is your negative and connects to the cell negative through two N-channel MOSFETs, controlled by an ABLIC S-8252 cell protection IC.

When using the 4-pin blade connector to charge at 8.4V, or discharged for that matter, the cells will still be protected (not balanced actively), and you're fully bypassing the USB charging circuit.

Hope that helps!

**Comment by shmick** [comment]
Thijs,

Thanks for the info! 

My plan is to use some small solar panels to keep the Braunit battery topped up in an Ikea Fyrtur shade using a TP5100 connected to the battery.

Thanks again.

**Comment by Thijsiez** [comment]
That sounds like a great improvement! I have two of the FYRTUR myself and I'm pretty sure that if you open up the side with the battery, it exposes a black and red lead to the battery connector :)
